### ISSUE TITLE
Create PathFinder full node instance

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/beerus#1]
# Description

The light client needs a connection to a full node in order to operate.
Note that this connection is trustless and can be insecure, since the light client verifies storage proofs.

# Acceptance criteria

- instance of PathFinder is created on AWS
- instance is publicly accessible

**Comment by LucasLvy** [comment]
![Screenshot from 2022-12-06 10-49-32](https://user-images.githubusercontent.com/70894690/205877511-6d5b508b-ada7-4f98-a906-f3cba20938bb.png)
Done
