### ISSUE TITLE
feat: Ethereum RPC "get_logs" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#138]
# Description

Implement "get_logs" Ethereum RPC call

Helios implmentation: https://github.com/a16z/helios/blob/ac8a145ae33e72b62e017749fd0d3e1887d3999e/client/src/rpc.rs#L101

# Acceptance Criteria

- Beerus can query a Ethereum's tx logs
- Associated cli command
- Associated rest api wrapper
- Helios integration
- Units tests
- Integration tests

**Comment by fkrause98** [comment]
I'll be working on this one.
