### ISSUE TITLE
feat: Ethereum RPC "get_transaction_count" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#140]
# Description

Implement "get_transaction_count" Ethereum RPC call

Helios implmentation: https://github.com/a16z/helios/blob/ac8a145ae33e72b62e017749fd0d3e1887d3999e/client/src/rpc.rs#L59

# Acceptance Criteria

- Beerus can query a Ethereum's txs count
- Associated cli command
- Associated rest api wrapper
- Helios integration
- Units tests
- Integration tests

**Comment by ftupas** [comment]
Hello there, may I take this one?

**Comment by ftupas** [comment]
I've created a [pr](https://github.com/a16z/helios/pull/166) on helios for this RPC method. I'm preparing the pr for when it's merged

**Comment by danilowhk** [comment]
Ok! :)
