### ISSUE TITLE
feat: Initial Starknet RPC "get_state_update" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#150]
# Description

Implement "get_state_update" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/a6d864fb0b02a9b530283148047ab5027ce4d295/starknet-providers/src/jsonrpc/mod.rs#L155

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Units tests
- Integration tests

**Comment by fkrause98** [comment]
Can I work on this one?

**Comment by danilowhk** [comment]
Assigned :)
