### ISSUE TITLE
feat: Initial Starknet RPC "get_transaction_receipt" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#152]
# Description

Implement "get_transaction_receipt" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/a6d864fb0b02a9b530283148047ab5027ce4d295/starknet-providers/src/jsonrpc/mod.rs#L215

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Units tests
- Integration tests

**Comment by richwarner** [comment]
Can this one be assigned to me please?

**Comment by danilowhk** [comment]
Assigned

**Comment by fkrause98** [comment]
Hey, can I work on this one?
I think it'd be useful for #179

**Comment by richwarner** [comment]
Yes, sure no problem you can take it.
