### ISSUE TITLE
feat: Initial Starknet RPC "estimate_fee" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#156]
# Description

Implement "estimate_fee" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/a6d864fb0b02a9b530283148047ab5027ce4d295/starknet-providers/src/jsonrpc/mod.rs#L310

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Units tests
- Integration tests

**Comment by ftupas** [comment]
Hello, may I take this one?

**Comment by danilowhk** [comment]
Assigned!
