### ISSUE TITLE
feat: Initial Starknet RPC "syncing" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#158]
# Description

Implement "syncing" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/a6d864fb0b02a9b530283148047ab5027ce4d295/starknet-providers/src/jsonrpc/mod.rs#L358

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Units tests
- Integration tests

**Comment by dpinones** [comment]
Hello there, may I take this one?
