### ISSUE TITLE
feat: Initial Starknet RPC "add_deploy_transaction" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#162]
# Description

Implement "add_deploy_transaction" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/a6d864fb0b02a9b530283148047ab5027ce4d295/starknet-providers/src/jsonrpc/mod.rs#L425

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Units tests
- Integration tests

**Comment by dpinones** [comment]
Hello there, may I take this one?

**Comment by danilowhk** [comment]
Assgined
