### ISSUE TITLE
feat: Add Verification Layer to "Starknet : get_block_hash_and_number"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#181]
- Add a Block / Root verification on top of the data received from the "starknet-rs" Client.
- Block / Root verification can be done through validation of Starknet_Block info form L1 and also utilizing storage_proofs(maybe it's not needed) from this issue: https://github.com/keep-starknet-strange/beerus/issues/62

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by irisdv** [comment]
Can work on this one
