### ISSUE TITLE
feat: Add Verification Layer to "Starknet : get_transaction_by_block_and_index"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#183]
- Add a Transaction / Block / Root(if needed) verification on top of the data received from the "starknet-rs" Client.
- Transaction / Block / Root verification can be done through validation of Starknet_Block info form L1 and also utilizing storage_proofs(maybe it's not needed) from this issue: https://github.com/keep-starknet-strange/beerus/issues/62

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by phklive** [comment]
Would be happy to take on this issue.

**Comment by danilowhk** [comment]
Assigned!
