### ISSUE TITLE
feat: migrate from `beerus_rest_api` to `beerus-rpc`

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/beerus#192]
# Feature Request

Proposal to migrate the `beereus_rest_api` to `beerus-rpc` server that adheres to this StarkNet JSON-RPC Specification:
- https://github.com/starkware-libs/starknet-specs
 
Dependency choice up to implementer. 

Suggestion - https://github.com/paritytech/jsonrpsee
- 371 stars
- looks to be actively maintained
- used by reth, kakarot-rpc, pathfinder

**Comment by phklive** [comment]
I would also be glad to contribute on this improvement of the codebase.

**Comment by danilowhk** [comment]
Hey @phklive definitely, will assign it to you :)

**Comment by dlight** [comment]
Hi, I just talked to @phklive, we can work on this issue together

**Comment by drspacemn** [comment]
Have you guys looked into what OpenAPI adapters you'll be using to replace `rocket_okapi`?

This looked like a good option: https://docs.rs/utoipa/latest/utoipa

**Comment by drspacemn** [comment]
Editing this issue to reflect the move to deprecation of `rest_api` in favor of `json_rpc` implementation

**Comment by Eikix** [comment]
Why is this assigned to me ;pp

**Comment by dlight** [comment]
I think @drspacemn intended to assing me (I'm the other Elias)

**Comment by danilowhk** [comment]
@all-contributors please add @phklive for feature contribution

**Comment by phklive** [comment]
We are almost there, I will close this issue because it is not relevant anymore.
