### ISSUE TITLE
feat: Make Beerus Wasmable

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#193]
# Feature Request

Successfully build Beerus into Wasm. 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by drspacemn** [comment]
I can take this issue
