### ISSUE TITLE
Implement `get_contract_storage_proof`

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/beerus#20]
# Description
In order to verify the value sent by the full node we need the contract storage proof.

# Acceptance criteria
- Beerus can query a starknet full node to get the contract storage root
- Associated cli command
- Associated rest api wrapper
- Starknet.rs full node integration
- Units tests
- Integration tests

**Comment by Kelvyne** [comment]
Hey, would love to do this.
