### ISSUE TITLE
feat: Beerus Config File

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#206]
# Feature Request

**Describe the Feature Request**

Take config from config file in addition to environment variables.

**Describe Preferred Solution**
On process start up initially look for config file(default for `~/.beerus/beerus.toml`) to parse for startup variables. If not found, parse from env(as we are now)

//example beerus.toml
```
[environment]
network = "goerli"
log_level = "info"
data_dir = ".beerus/tmp"
fetch_seconds = 5

[mainnet]
consensus_rpc = "https://www.lightclientdata.org"
execution_rpc = "https://eth-mainnet.g.alchemy.com/v2/XXXXX"
starknet_rpc="https://mainnet.infura.io/v3/XXXXXX"

[goerli]
consensus_rpc = "http://testing.prater.beacon-api.nimbus.team"
execution_rpc = "https://eth-goerli.g.alchemy.com/v2/XXXXX"
starknet_rpc="https://starknet-goerli.infura.io/v3/XXXXXX"
```

**Describe Alternatives**

currently parse from env

**Comment by phklive** [comment]
i'll do that

**Comment by ptisserand** [comment]
I think if a config is defined in an environment variable it should be used instead of the one in the config file.
For me it's the expected behavior.

Can I work on this issue?

**Comment by drspacemn** [comment]
That sounds good to me for env_variable. 

Assigning to you.

**Comment by drspacemn** [comment]
@ptisserand any update here? This will help w/ the no-std conversion, and if you haven't taken it I can implement

**Comment by ptisserand** [comment]
Really sorry I didn't take time to start working on it.

**Comment by phklive** [comment]
You closed this issue right @drspacemn ?

**Comment by phklive** [comment]
If yes i will close.

**Comment by phklive** [comment]
Issue closed.
