### ISSUE TITLE
fix: Fix error when calling "starknet_state_root" and "starknet_last_proven_block"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#209]
# Bug Report
Currently, when calling "starknet_state_root" and "starknet_last_proven_block" on the "start" thread:

https://github.com/danilowhk/beerus/blob/57a47dd37091ba97263248955318681de0393fdb/beerus_core/src/lightclient/beerus.rs#L118

and 

https://github.com/danilowhk/beerus/blob/57a47dd37091ba97263248955318681de0393fdb/beerus_core/src/lightclient/beerus.rs#L124

Currently we can confirm that the helios_client is working well within the thread/loop 

https://github.com/danilowhk/beerus/blob/57a47dd37091ba97263248955318681de0393fdb/beerus_core/src/lightclient/beerus.rs#L132

And when calling "starknet_state_root" and "starknet_last_proven_block" with the wrong contract address, it returns 0.

So I believe the issue is within the functions itself(it could be because the function was moved from "beerus" to "beerus.ethereum_client."

**Beerus version:**

0.1.0

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by RajeshRk18** [comment]
Can we lazy static the DEFAULT_STARKNET_CORE_CONTRACT_ADDRESS?

**Comment by RajeshRk18** [comment]
Can I try solving this issue?
