### ISSUE TITLE
feat: Migrate Starknet : chain_id" from "beerus_rest_api" to "beerus_rpc"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#212]
# Feature Request

**Describe the Feature Request**

We are deprecating "beerus_rest_api" and now migrating all the api endpoints to "beerus_rpc".

Migrate chain_id and add tests on beerus_rpc.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by dpinones** [comment]
Hello there, may I take this one?

**Comment by phklive** [comment]
I done it already.

We are syncing with @danilowhk so this does not happen sorry @dpinones.

**Comment by danilowhk** [comment]
@phklive please tag the PR when u have it so we can close the issue
