### ISSUE TITLE
feat: Migrate Starknet : get_block_transaction_count from "beerus_rest_api" to "beerus_rpc"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#222]
# Feature Request

**Describe the Feature Request**

We are deprecating "beerus_rest_api" and now migrating all the api endpoints to "beerus_rpc".

Migrate get_block_transaction_count and add tests on beerus_rpc.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by dpinones** [comment]
Hello there, may I take this one?
