### ISSUE TITLE
feat: Migrate Starknet : get_transaction_by_block_id_and_index from "beerus_rest_api" to "beerus_rpc"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#230]
# Feature Request

**Describe the Feature Request**

We are deprecating "beerus_rest_api" and now migrating all the api endpoints to "beerus_rpc".

Migrate get_transaction_by_block_id_and_index and add tests on beerus_rpc.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by danilowhk** [comment]
Assigned!

**Comment by phklive** [comment]
lgtm
