### ISSUE TITLE
feat: Migrate Starknet : get_contract_storage_proof from "beerus_rest_api" to "beerus_rpc"

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#235]
# Feature Request

**Describe the Feature Request**

We are deprecating "beerus_rest_api" and now migrating all the api endpoints to "beerus_rpc".

Migrate get_contract_storage_proof and add tests on beerus_rpc.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by dlight** [comment]
Hi, I would like to take this issue.

**Comment by phklive** [comment]
Hey @dlight do you need any help to close this issue? How is it advancing?

**Comment by phklive** [comment]
I will take it

**Comment by phklive** [comment]
merged
