### ISSUE TITLE
dev: Documentation for RPC 

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#244]
**Enhancement:**
Add documentation similar to `kakarot_rpc`

**Reference:** 
- https://github.com/sayajin-labs/kakarot-rpc/blob/main/docs/methods/eth_getBlockByNumber.md
- https://github.com/a16z/helios/blob/master/rpc.md

**Comment by drspacemn** [comment]
method documentation can live here:
https://github.com/keep-starknet-strange/beerus/tree/main/docs/beerus-rpc

**Comment by dragan2234** [comment]
hey @drspacemn can I get assigned to this one, seems like it would give me nice intro to the project :)

**Comment by phklive** [comment]
Hey @dragan2234 do you still want to build the documentation for Beerus, I am making a presentation at the moment that could potentially be useful for documentation too.

**Comment by dragan2234** [comment]
hey @phklive please assign this to somebody else, I'm busy with another project right now :)

**Comment by dpinones** [comment]
Hey guys, I would like to take this.

**Comment by phklive** [comment]
Absolutely, if you have some ideas to share or that you need feel free to hmu.

**Comment by drspacemn** [comment]
Merging this w/ ticket #352
