### ISSUE TITLE
bug: JsonRPC Error Handling

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#276]
# Bug Report

**Beerus version:**

latest

**Current behavior:**

rpc methods have `unwrap()` which results in a rust panic if response is an Error. `unwrap` should only be used when there is never going to be an Error surfaced from the rpc method.

**Expected behavior:**

rpc methods should not cause a rust panic on error and should provide a meaningful response.

**Steps to reproduce:**

On any invoked method, wrap response in Err() instead of Ok() to see a rust panic trying to `unwrap()` an Error.

**Related code:**

Example method with `unwrap()`:

```
async fn starknet_l1_to_l2_message_cancellations(&self, msg_hash: U256) -> Result<U256> {
        Ok(self
            ._beerus
            .starknet_l1_to_l2_message_cancellations(msg_hash)
            .await
            .unwrap())
    }
```

Here's a hard coded Err response to cause the above to panic:
```
let call_response = self
            .ethereum_lightclient
            .read()
            .await
            .call(&call_opts, BlockTag::Latest)
            .await?;
        // Ok(U256::from_big_endian(&call_response))
        Err(eyre::ErrReport::msg(U256::from_big_endian(&call_response)))
```

**Other information:**

Will submit PR to fix rpc methods by replacing `unwrap()` with a custom jsonrpsee error that is passed the error report as a string:
```
async fn starknet_l1_to_l2_message_cancellations(&self, msg_hash: U256) -> Result<U256> {
        self
            ._beerus
            .starknet_l1_to_l2_message_cancellations(msg_hash)
            .await
            .map_err(|e| Custom(e.to_string()))
    }
```

The above is able to handle an error by generating a custom error based on report and not panic:
```
{"jsonrpc":"2.0","error":{"code":-32001,"message":"Custom error: 1652197619"},"id":1}%
```

**Comment by drspacemn** [comment]
This looks good to me. To add to your proposal, I think we should define common error types that we expect to see often, the same way that Papyrus does here:
https://github.com/starkware-libs/papyrus/blob/c1c16a12e4d9379b542423bbf20f77188c654577/crates/papyrus_gateway/src/api.rs#L42

Note they also return that error in the result:
https://github.com/starkware-libs/papyrus/blob/c1c16a12e4d9379b542423bbf20f77188c654577/crates/papyrus_gateway/src/lib.rs#L268

**Comment by Aragar199** [comment]
Thanks for the examples, this is great. Couple of questions:

Where can I find a list of common error types that we expect to see often using beerus rpc methods? Or should I create a template and we add common errors as a TODO when they are encountered?

**Comment by phklive** [comment]
Correct error handling has been added we can close this issue.
