### ISSUE TITLE
dev: Cargo Update

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#304]
We have a vulnerability in our dependency graph: https://github.com/keep-starknet-strange/beerus/security/dependabot

We need to run: `cargo update` and test all functionality to remove

**Comment by dpinones** [comment]
Hello there, may I take this one?

**Comment by dpinones** [comment]
I can't access the link because a 404 error appears. 
I ran the `cargo update` command and the dependencies in the Cargo.lock file were updated to the latest version. 
Then, I ran the tests and all of them passed successfully. 
Is there anything else I need to do?

**Comment by drspacemn** [comment]
I was hoping that would fix the dependency issue, but it looks like it's something else pinned in our `helios` dependency(`chrono` -> `time`): 
- https://github.com/keep-starknet-strange/beerus/security/dependabot
- https://github.com/keep-starknet-strange/beerus/blob/ce16f268e5df4613dc5a487837f7f316e69ad160/Cargo.lock#L797

Do you know another way to remove the nested dependency pin?

**Comment by drspacemn** [comment]
appears to have mysteriously resolved itself
