### ISSUE TITLE
feat: migration to BlockId

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#351]
# Feature Request

The way we currently handle [block id](https://github.com/keep-starknet-strange/beerus/blob/56026b7579078a2ecb725e2a8d434b060bce6a50/examples/beerus-rpc/starknet_getEstimateFee.hurl#L7) is not compliant with the ecosystem([example](https://github.com/eqlabs/pathfinder/blob/1112b7532a998c5237df4dd8d76e96b7097c2011/doc/rpc/rpc_examples_v03.sh#L26))

Beerus needs to handle a `BlockId` similar to other R[PC Providers](https://github.com/starkware-libs/papyrus/blob/1ca9d93f5830b6e883e2ed9d4efc84fc2c8154e5/crates/papyrus_gateway/src/api.rs#L37)

**Describe Preferred Solution**

- Use `starknet-rs` [jsonrpc-models](https://github.com/xJonathanLEI/starknet-rs/blob/e72cc0a4b3ea67c7691ebec58300da3c21f0abb2/starknet-providers/src/jsonrpc/models/mod.rs#L106)    
    
**Describe Alternatives**

- implement a Deserialize/Serialize implementation in `beerus-core` for `BlockId` that rpc, cli can import and use 
    - [ex part 1 ](https://github.com/starkware-libs/papyrus/blob/1ca9d93f5830b6e883e2ed9d4efc84fc2c8154e5/crates/papyrus_gateway/src/api.rs#L37) [ex part 2](https://github.com/starkware-libs/papyrus/blob/1ca9d93f5830b6e883e2ed9d4efc84fc2c8154e5/crates/papyrus_gateway/src/api.rs#L65)  [ex part 3](https://github.com/starkware-libs/papyrus/blob/1ca9d93f5830b6e883e2ed9d4efc84fc2c8154e5/crates/papyrus_gateway/src/api.rs#L37) 

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Aragar199** [comment]
@drspacemn I'll take this.

**Comment by phklive** [comment]
How is it going with the BlockId ?

**Comment by Aragar199** [comment]
> How is it going with the BlockId ?

It's done, need https://github.com/keep-starknet-strange/beerus/pull/363 merged first. Depends on updated starknet-rs library.

**Comment by phklive** [comment]
Now that the starknet-rs upadte has been merged #364 you should be able to close this one too.
