### ISSUE TITLE
feat: "eth_" RPC Proxy

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#354]
Implement a proxy middleware that routes "eth_" rpc calls to the helios rpc server.

**Describe Preferred Solution**

By default `beerus-rpc` inits 2 rpc servers `beerus -> 3030` `helios -> 3031`. Client will need to manage both endpoints if they require both "eth_" and "starknet_" endpoints

Impl:
- proxy "eth_" received on 3030  to helios on 3031
- `jsonrpsee` can extend middleware services like `tower` proxies
- or another http proxy service that can handle this routing

**Related Code**

[potential impl](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http_proxy_middleware.rs)

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by phklive** [comment]
Gonna take this one

**Comment by phklive** [comment]
Closed after research and jsonrpsee preventing proxy implementation
