### ISSUE TITLE
feat: wrap checkpoint options from Helios for better sync managment and UX

### ISSUE THREAD

**Issue by glihm** [keep-starknet-strange/beerus#378]
# Feature Request

**Describe the Feature Request**

Recently we merged a PR upgrading Helios with a fix where now the checkpoint of Helios node is correctly saved in data dir.

However, this also may introduce some sync problems. For this reason we have to be able to request beerus to clear the checkpoint, which triggers a re-sync of the Helios node.

**Describe Preferred Solution**

As default beerus should keep the node state, and clear it if requested by the user when starting.

**Describe Alternatives**

**Related Code**

https://github.com/a16z/helios/blob/master/README.md#additional-options

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by glihm** [comment]
@phklive you can assign it to me it's part of helios rework. :)

**Comment by dpinones** [comment]
assigned!

**Comment by glihm** [comment]
PR ready, it will be closed on PR merge.
