### ISSUE TITLE
feat: Update beerus-rpc add_declare_transaction RPC to handle V2

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#380]
# Feature Request

With update to starknet-rs, we are only handling V1 in add_declare_transaction. Update beerus-rpc to handle both V1 and V2.

**Describe Preferred Solution**

Update add_declare_transaction to handle both versions of declare request.

if version is "1", then V1 declare transaction
if version is "2", then V2 declare transaction

https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#declare_v2

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by naelob** [comment]
Hey @Aragar199
Im willing to take it let me know the basic steps to start working on it. like should i create my own branch work on it and then submit the PR ?

**Comment by phklive** [comment]
Ablsolutely assigned.

**Comment by Aragar199** [comment]
> Hey @Aragar199 Im willing to take it let me know the basic steps to start working on it. like should i create my own branch work on it and then submit the PR ?

Hey @naelob sorry I missed this comment. Yes, you can fork the repo, create your own branch, then submit a PR per our [contributing guidelines](https://github.com/keep-starknet-strange/beerus/blob/main/docs/CONTRIBUTING.md). How is progress going on this issue?

**Comment by phklive** [comment]
Can you take care of this one @Aragar199 ?

**Comment by Aragar199** [comment]
Sure thing, please assign @phklive

**Comment by phklive** [comment]
super
