### ISSUE TITLE
feat: Update beerus-cli add_declare_transaction RPC to handle V2

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#381]
# Feature Request

With update to starknet-rs, we are only handling V1 in add_declare_transaction. Update beerus-cli to handle both V1 and V2 and update tests.

**Describe Preferred Solution**

Update add_declare_transaction to handle both versions of declare transaction.

if version is "1", then V1 declare transaction
if version is "2", then V2 declare transaction

https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#declare_v2

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by naelob** [comment]
Hey ! @Aragar199 
Let me know if i can take this one too.

**Comment by naelob** [comment]
Thanks

**Comment by naelob** [comment]
According to starknet docs :

version : The transaction’s version. The value is 1. When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases. Transaction version 0 is deprecated and will be removed in a future version of Starknet.
-- | -- | --
I want to be sure if this is the same version as the version we're talking about.

My question is can I use this version variable to target v1 or v2  OR the version you're talking about need to be captured in an another variable ? 

Thanks

**Comment by Aragar199** [comment]
> According to starknet docs :
> 
> version : The transaction’s version. The value is 1. When the fields that comprise a transaction change, either with the addition of a new field or the removal of an existing field, then the transaction version increases. Transaction version 0 is deprecated and will be removed in a future version of Starknet. -- | -- | -- I want to be sure if this is the same version as the version we're talking about.
> 
> My question is can I use this version variable to target v1 or v2 OR the version you're talking about need to be captured in an another variable ? @Aragar199 Thanks

Yes, this is the same version as the version we are talking about.

**Comment by naelob** [comment]
> 

Ok I decided to push my updates but after git commit my files are still in staging while no errors is generated : 
<img width="986" alt="Capture d’écran 2023-04-19 à 19 50 53" src="https://user-images.githubusercontent.com/39710677/233159030-5d7df855-1ad6-438c-b5b0-7a8c1c124647.png">
<img width="986" alt="Capture d’écran 2023-04-19 à 19 51 09" src="https://user-images.githubusercontent.com/39710677/233159052-a2c3387c-e8da-4064-a828-5f8dbe93b272.png">
Do you know where it comes from ?

**Comment by phklive** [comment]
You could have a clippy or fmt error, it won't enable you to push.

**Comment by naelob** [comment]
From what i can see its an fmt error but I cant understand it

**Comment by naelob** [comment]
I opened a PR for this task but I saw that beerus-cli will be removed so Should I go away from this one and focus on beerus-rpc ?

**Comment by phklive** [comment]
Hey Nael, indeed we discussed the fact that the Beerus-cli will be removed this week. Sorry for this misunderstanding.
Hope you were able to learn some stuff and that well build some great stuff together.
