### ISSUE TITLE
feat: Remove 'too many arguments' from clippy error

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#382]
# Feature Request

add_declare_transaction takes 8 arguments including &self which causes and error with clippy when upgrading to V2 datatype.

**Describe Preferred Solution**

Remove too many arguments check from clippy.

**Describe Alternatives**

Maybe there is a workaround, but value of checking how many arguments are in a function seems excessive.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by phklive** [comment]
This is related to the cli right?

**Comment by phklive** [comment]
Can you take care of this one @Aragar199?

**Comment by Aragar199** [comment]
Yeah sure, go ahead and assign @phklive

**Comment by phklive** [comment]
super

**Comment by Aragar199** [comment]
Didn't need to do this. Rendered irrelevant due to starknet-rs update see https://github.com/keep-starknet-strange/beerus/pull/485/files
