### ISSUE TITLE
feat: Dockerize Beerus

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#385]
# Feature Request

**Describe the Feature Request**

Run beerus in a Docker container and enable it to run with github actions.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by robinstraub** [comment]
I can work on this alongside #387 with @glihm

**Comment by dpinones** [comment]
assigned

**Comment by glihm** [comment]
Ready to work with you @robinstraub. 👍🏻
