### ISSUE TITLE
feat: Create bash script to run all hurl files in correct sequence

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#387]
# Feature Request

**Describe the Feature Request**

We will need a bash script to run all hurl files in the right sequence to hit the beerus instance in the CI. 

It is important to note that some endpoints will need live data ( considering that helios only indexes the last 64 blocks ). For example eth_getBlockByNumber will only return a block if it has been indexed by Helios.

Some endpoints will return error if given incorrect or un-indexed data as params.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

Here the results of the hurl update runs gist 1 & gist 2 will give you an idea of what works and what doesn't and what you need to work on. ( gist 2 should be the most up to date, gist 1 can give you guidance in case gist 2 doesn't ). 
[run1](https://gist.github.com/phklive/aac18fc90a6c5157b0c92ffbc6d20c7c)
[run2](https://gist.github.com/phklive/90252350b7932243810ea727fcbdb5d5)

**Comment by robinstraub** [comment]
I would love to, please assign it to me.

**Comment by phklive** [comment]
No need for a bash script to run all hurl files in sequence but just use the right cli command.

`hurl --test ./*`
