### ISSUE TITLE
feat: Implement Beerus hurl tests as github action / CI

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#388]
# Feature Request

**Describe the Feature Request**

Implement beerus hurl test as a github action / CI

Depends on:

- [ ] https://github.com/keep-starknet-strange/beerus/issues/387
and 
- [x] https://github.com/keep-starknet-strange/beerus/issues/384

That need to be closed and merged first.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by glihm** [comment]
@phklive this can be closed right? With work done lately by @Aragar199 and @robinstraub ?

**Comment by phklive** [comment]
If PR's from @Aragar199  for the fix and @robinstraub for the CI are merged then yes it will be closed.
