### ISSUE TITLE
feat: Add proper error handling on starknet rpc endpoints

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#397]
# Feature Request

**Describe the Feature Request**

We were previously figuring out the way to handle rpc errors on Beerus hence incorrect implementation on endpoints implemented before we managed to settle for a specific way to handle ( we took example on pathfinder error handling ) errors as seen here:
- [Pathfinder error struct](https://github.com/eqlabs/pathfinder/blob/a4f08758862cdfee5fed5ec093305d8b1bea78d2/crates/rpc/src/error.rs#L9)
- [Beerus error struct](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-rpc/src/api.rs#L21)

The mission is to update all rpc endpoints to support correct error handling, a good understanding of how the rpc works and all the methods the rpc implements is required considering you will need to understand what errors are returned by each method and in what situation. ( remove unwraps, remove anyhow, etc... ) We must prevent beerus from crashing at all costs.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

Here are some additional ressources that could help: 
- [Beerus error handling in method](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-rpc/src/lib.rs#L79)

You can also take inspiration on Pathfinder:
- [Pathfinder repo](https://github.com/eqlabs/pathfinder)

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by dubzn** [comment]
I would like to take this one

**Comment by phklive** [comment]
assigned.

**Comment by phklive** [comment]
How are you doing with this one?

**Comment by dubzn** [comment]
Hey Paul, how you doing? I have this [PR](https://github.com/keep-starknet-strange/beerus/pull/402) ready for the review, and in case that is ok I implemented the error handling in a similar way in [this one](https://github.com/keep-starknet-strange/beerus/pull/408) (I wanted to validate that's why still in draft, actually, there is no work to be done in that)
