### ISSUE TITLE
dev: OpenRPC Client Generator

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#409]
Use the `open-rpc-generator` (https://github.com/open-rpc/generator) to autogenerate a rust RPC client based on the https://github.com/starkware-libs/starknet-specs and complete the mocks required to make the RPC comply.

**Comment by glihm** [comment]
Looks like we will stick to `starknet-rs` generated code for now. @drspacemn we will attempt in a @dubzn PR to match the types from `starknet-rs` to see how that fits.

**Comment by glihm** [comment]
@drspacemn @phklive what do you think? Do we need to dev the client generator or better stay focus on code and use `starknet-rs` types?
