### ISSUE TITLE
bug: Beerus stops processing incoming connections on hosts with less than 3 cpu

### ISSUE THREAD

**Issue by robinstraub** [keep-starknet-strange/beerus#438]
# Bug Report

**Beerus version:**

 v0.2.0

**Current behavior:**

*edit: this issue only happens in a Docker container*

When running Beerus on a host with 2 logical cpus, under some specific circumstances (some method calls sent at a specific time), Beerus stops reacting to incoming connections, without logging error, and without panicking. Subsequent RPC calls thus result in timeouts. 

When the cpu count gets lower (1 or fraction of a cpu), Beerus fails to synchronize the state root and the last proven block (in what I refer to as "[the loop](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/beerus.rs#L136)"). This behavior also leads to Beerus stopping to react to incoming connections as with 2 cpus.

**Expected behavior:**

As a light client, Beerus should not require a host with 3 logical CPUs to operate.

**Steps to reproduce:**

1. Execute Beerus on a host with 2 logical cpus or less
2. Call a Beerus RPC method that interacts with the starknet core contract (e.g. `starknet_l1_to_l2_message_nonce`), while Beerus synchronization task (the loop) is calling it (the task calls it [here](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/beerus.rs#L147))

The easiest way to achieve this is to run Beerus inside a Docker container so the CPU can be restricted (`docker run --cpus=2 [...]`), you can find a working docker configuration (Dockerfile and docker-compose.yml) on [PR 421](https://github.com/keep-starknet-strange/beerus/pull/421).

**Related code:**

N/A

**Other information:**

This behavior has been a bit erratic and Beerus randomly worked with 2 cpu. After some investigation, when RPC keeps working on 2CPU (e.g. allowing all hurl tests to be conducted without timeout), this happens because Beerus task (the loop) panics. Here is a log:

```
beerus-beerus-rpc-1  | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: out of sync: 12 slots behind
beerus-beerus-rpc-1  | 
beerus-beerus-rpc-1  | Location:
beerus-beerus-rpc-1  |     /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/convert/mod.rs:726:9', /beerus/crates/beerus-core/src/lightclient/beerus.rs:142:26
```

However this is way less common than Beerus just stop accepting new connections.

**Comment by Aragar199** [comment]
Can you assign this to me?
