### ISSUE TITLE
feat: Deprecate eth_ endpoints from beerus-rpc

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#439]
# Feature Request

**Describe the Feature Request**

After discussion exposing eth_ endpoints through Beerus is not useful for the end user, but very useful for verification of data internally to Beerus, hence removal of the exposure of eth_ endpoints

**Describe Preferred Solution**

Remove eth_ endpoints from beerus-rpc

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by glihm** [comment]
Discussed at the CC this week, we are keeping them. :+1:
