### ISSUE TITLE
Increase Beerus core coverage to 90%

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/beerus#46]
# Description

Beerus needs to be fully tested so we need  to increase the test coverage

# Acceptance criteria

Beerus core coverage is at least at 90%

**Comment by Kelvyne** [comment]
Not sure I can reach 90% but I'd like to give it a try :)

**Comment by abdelhamidbakhta** [comment]
> Not sure I can reach 90% but I'd like to give it a try :)

Do your best.
We are not that far actually. to be clear this is ticket is about the core module only.
https://app.codecov.io/gh/keep-starknet-strange/beerus
We are at 73% for now on the beerus_core

**Comment by Kelvyne** [comment]
Hey. Seems like this is not that useful anymore, coverage is at 89%. I'll work on something else.
