### ISSUE TITLE
feat: Research the creation of a Devnet for Beerus

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#475]
# Feature Request

**Describe the Feature Request**

Research the creation of a Devnet for Beerus, enabling local testing on predictable data.

This will have multiple benefits for: 
- Internal Testing
- User utilisation
- CI

**Comment by robinstraub** [comment]
## Mainnet - Devnet comparison

| Group      | Method                                   | Status             | devnet             | notes                                                                                                                                                                                                                                                                           |
|------------|------------------------------------------|--------------------|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| additional | starknet_addDeclareTransaction           | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| additional | starknet_addDeployAccountTransaction     | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| additional | starknet_addInvokeTransaction            | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| additional | starknet_getContractStorageProof         | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| additional | starknet_l1_to_l2_message_cancellations  | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: rpc error: rpc error on method: create_access_list, message: (code: -32602, message: BlockOutOfRangeError: block height is 17285016 but requested was 17285060, data: None)`           |
| additional | starknet_l1_to_l2_message_nonce          | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: rpc error: rpc error on method: create_access_list, message: (code: -32602, message: BlockOutOfRangeError: block height is 17285016 but requested was 17285089, data: None)`           |
| additional | starknet_l1_to_l2_messages               | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: rpc error: rpc error on method: create_access_list, message: (code: -32602, message: BlockOutOfRangeError: block height is 17285016 but requested was 17285094, data: None)`           |
| additional | starknet_l2_to_l1_messages               | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: rpc error: rpc error on method: create_access_list, message: (code: -32602, message: BlockOutOfRangeError: block height is 17285016 but requested was 17285099, data: None)`           |
| eth        | eth_blockNumber                          | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_call                                 | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_chainId                              | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_coinbase                             | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_estimateGas                          | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_gasPrice                             | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getBalance                           | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getBlockByHash                       | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getBlockByNumber                     | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getBlockTransactionCountByHash       | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getBlockTransactionCountByNumber     | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getCode                              | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getLogs                              | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getStorageAt                         | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getTransactionByBlockHashAndIndex    | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getTransactionByHash                 | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getTransactionCount                  | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_getTransactionReceipt                | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_maxPriorityFeePerGas                 | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| eth        | eth_sendRawTransaction                   | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| eth        | eth_syncing                              | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_blockHashAndNumber              | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_blockNumber                     | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_call                            | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_chainId                         | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getBlockTransactionCount        | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getBlockWithTxHashes            | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getBlockWithTxs                 | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getClass                        | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getClassAt                      | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JSON-RPC error: code=-32602, message="Got invalid value for parameter: "'0x40688250ef0074b4c9e1057b19f9b62139ac28179c7d35e2dae5abad909d558' does not match '^0x0[a-fA-F0-9]{1,63}$'""` |
| starknet   | starknet_getClassHashAt                  | :heavy_check_mark: | :heavy_check_mark: | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JSON-RPC error: code=-32602, message="Got invalid value for parameter: "'0x7f38ab7537dbb5f8dc2d049d441f2b250c2186a13d943b8467cfa86b8dba12b' does not match '^0x0[a-fA-F0-9]{1,63}$'""` |
| starknet   | starknet_getEstimateFee                  | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getEvents                       | :x:                | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getNonce                        | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JSON-RPC error: code=-32602, message="Got invalid value for parameter: "'0x10b6c96d364cf182964fbd4a3438a5ae84cab990770c07994f9cb99fd26f6dc' does not match '^0x0[a-fA-F0-9]{1,63}$'""` |
| starknet   | starknet_getStateUpdate                  | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getStorageAt                    | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getTransactionByBlockIdAndIndex | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getTransactionByHash            | :heavy_check_mark: | :x:                |                                                                                                                                                                                                                                                                                 |
| starknet   | starknet_getTransactionReceipt           | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JSON-RPC error: code=-32602, message="Got invalid value for parameter: "'0x4c1672e824b5cd7477fca31ee3ab5a1058534ed1820bb27abc976c2e6095151' does not match '^0x0[a-fA-F0-9]{1,63}$'""` |
| starknet   | starknet_pendingTransactions             | :heavy_check_mark: | :x:                | `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Call(Custom(ErrorObject { code: ServerError(38), message: "Failed to fetch pending transactions", data: None }))', crates/beerus-rpc/src/lib.rs:693:32`                                |
| starknet   | starknet_syncing                         | :heavy_check_mark: | :heavy_check_mark: |                                                                                                                                                                                                                                                                                 |

**Comment by drspacemn** [comment]
Action Item: 
- pick a block to fork from
- run all tests against deterministic block fork
