### ISSUE TITLE
feat: Add docker image to Beerus release

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/beerus#477]
# Feature Request

**Describe the Feature Request**

All new Beerus releases should include a dockerized version of Beerus, enabling users to quickly spin up Beerus using Docker

**Comment by robinstraub** [comment]
Madara has a cool workflow which builds and push a docker image to the github container registry: https://github.com/keep-starknet-strange/madara/blob/main/.github/workflows/docker.yml 

Beerus CI is already able to produce a docker image (see this workflow: https://github.com/keep-starknet-strange/beerus/blob/main/.github/workflows/ci.yml), so this issue can be addressed by copying madara workflow and configuring the authentication token
