### ISSUE TITLE
dev: example recipes

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#496]
Create a set of runnable recipes on how to implement beerus for use.

Ref: https://github.com/a16z/helios/tree/master/examples

**Comment by Aragar199** [comment]
1. Create a basic implementation of Beerus lightclient example runnable https://github.com/a16z/helios/blob/master/examples/basic.rs

2. Add call execution using starknet_call.hurl example as reference https://github.com/keep-starknet-strange/beerus/blob/main/examples/beerus-rpc/starknet/starknet_call.hurl (Should have similar logic using helios example https://github.com/a16z/helios/blob/master/examples/call.rs)

3. Add client.rs Beerus build instructions using helios client example as reference https://github.com/a16z/helios/blob/master/examples/client.rs

4. Add example runnable instructions to Beerus README and link for visibility.

**Comment by tonypony220** [comment]
assign me please

**Comment by Aragar199** [comment]
@tonypony220 assigned, and thanks!
