### ISSUE TITLE
dev: add Helios test coverage

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#497]
Add tests to cover our initialization and use of the Helios Light Client:

[Codebase section](https://github.com/keep-starknet-strange/beerus/tree/feat/489-argent-verification/crates/beerus-core/src/lightclient/ethereum)

Current Coverage Report:
https://app.codecov.io/gh/keep-starknet-strange/beerus/tree/main/crates%2Fbeerus-core%2Fsrc%2Flightclient%2Fethereum

**Comment by Aragar199** [comment]
@startup-dreamer assigned!
