### ISSUE TITLE
dev: add Beerus test coverage

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#498]
Add tests to cover our initialization and use of the Beerus Light Client:

[Codebase section](https://github.com/keep-starknet-strange/beerus/blob/feat/489-argent-verification/crates/beerus-core/src/lightclient/beerus.rs)

Current Coverage Report:
https://app.codecov.io/gh/keep-starknet-strange/beerus/blob/main/crates%2Fbeerus-core%2Fsrc%2Flightclient%2Fbeerus.rs

**Comment by 0xdorifto** [comment]
Hey @drspacemn I saw you reopened this issue. Can I work on it?

**Comment by Godspower-Eze** [comment]
Hey man!

Really nice you would like to work on this but I am currently working on it.
