### ISSUE TITLE
dev: add Config test coverage

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#499]
Add tests to cover our Config init for both env vars and config file:

[Codebase section](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/config.rs)

Current Coverage Report:
https://app.codecov.io/gh/keep-starknet-strange/beerus/blob/main/crates%2Fbeerus-core%2Fsrc%2Fconfig.rs

**Comment by somthn0somthn** [comment]
Please assign this to me
