### ISSUE TITLE
spike: ZK Light Client

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#514]
Follow up to Beerus CC Deep Dive - NEAR/Zpoken:
- go/no-go for wrapping Beeus in a ZK context
- being that we use storage proofs to prove L2 storage keys what functionality would this add to Beerus
- if go -> what protocols should we employ

References:
- [zpoken](https://github.com/ZpokenWeb3/zk-light-client-implementation)
- [near cc](https://www.youtube.com/watch?v=ScKr-yeSdqE)
- Beerus TG Members on zpoken @zkchain `Anton`

**Comment by somthn0somthn** [comment]
Thanks for setting this up. Should be interesting!

**Comment by somthn0somthn** [comment]
So, with my presentation about two weeks again, I think it is OK to close this current iteration of the issue. Happy to do another spike in the future though
