### ISSUE TITLE
dev: add beerus client init from config only

### ISSUE THREAD

**Issue by glihm** [keep-starknet-strange/beerus#516]
The initialization of beerus client using `BeerusLightClient::new` is for now [expecting two implementations](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/beerus.rs#L90), one for ethereum and one for starknet.

This issue aims at adding a new initialization function to spin up a beerus instance from the configuration only.

Currently, a new instance of beerus client looks like this:

```rust
  let config = Config::from_env();

  let ethereum_lightclient = HeliosLightClient::new(config.clone()).await?;
  let starknet_lightclient = StarkNetLightClientImpl::new(&config)?;

  let mut beerus = BeerusLightClient::new(
      config.clone(),
      Box::new(ethereum_lightclient),
      Box::new(starknet_lightclient),
  );

  beerus.start().await?;
```

A new initialization function may be invoked as follow:

```rust
let config = Config::from_env();
let mut beerus = BeerusLightClient::new(&config).await?;
beerus.start().await?;
```

Code related to that:

1. [Beerus light client initialization](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/beerus.rs#L90)
2. [Helios initialization](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/ethereum/helios_lightclient.rs#L232)
3. [Starknet light client](https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/starknet/mod.rs#L163)

Helios has async initialization but starknet light client does not. Therefore the new function may also be async.

**Comment by tonypony220** [comment]
Can I take this one?

**Comment by glihm** [comment]
Let's go @tonypony220!
