### ISSUE TITLE
dev: Pull #[cfg(test)] into testing dir

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/beerus#517]
Starting w/ Beerus Core -

Pull all tests currently in modules into dedicated testing dirs:
- https://github.com/keep-starknet-strange/beerus/blob/160ba0ac4b8160636f9476c7bf7450b7999316d1/crates/beerus-core/src/ethers_helper.rs#L103

to 

https://github.com/keep-starknet-strange/beerus/tree/main/crates/beerus-core/tests

**Comment by Godspower-Eze** [comment]
I could work on this
