### ISSUE TITLE
bug: the starknet_getStateUpdate rpc method is failing

### ISSUE THREAD

**Issue by robinstraub** [keep-starknet-strange/beerus#527]
**Current behavior**

The `starknet_getStateUpdate` method is failing when called with the associated hurl script. See the received response below:

```
{"jsonrpc":"2.0","error":{"code":520,"message":"Unknown error"},"id":0}
```

**Expected behavior**

Calling the `starknet_getStateUpdate` should result in a successful response as described in the [starknet specification](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/starkware-libs/starknet-specs/master/api/starknet_api_openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:darkMode%5D=true&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

**Steps to reproduce:**

1. Run Beerus locally: `cargo run --bin beerus-rpc`
2. Execute the associated hurl script: `hurl --ignore-asserts examples/beerus-rpc/starknet/starknet_getStateUpdate.hurl`

**Other information:**

The error can come either from a malformed request in the hurl file or from Beerus itself.

**Comment by tonypony220** [comment]
and this please
