### ISSUE TITLE
dev: remove block_id_string_to_block_id_type

### ISSUE THREAD

**Issue by Aragar199** [keep-starknet-strange/beerus#540]
With update to starknet-rs types we are using block id and no longer need the helper method block_id_string_to_block_id_type

Remove
crates/beerus-rpc/src/starknet_helper.rs/block_id_string_to_block_id_type

 and refactor tests to remove implementation and update to use starknet-rs block id type

**Comment by MdTeach** [comment]
Can I take this ?

**Comment by kasteph** [comment]
Can this be closed? #542 resolves this.
