### ISSUE TITLE
Implement beerusup command to install smoothly

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/beerus#6]
## Description

Add a handy script to install beerus.

Inspiration: https://github.com/a16z/helios/blob/master/heliosup/install

## Acceptance Criteria

- script is created and enable to install beerus very easily
- readme is modified with instructions (c.f https://github.com/a16z/helios#installing)

**Comment by drspacemn** [comment]
The functionality of install_beerus is dependent on a release process that includes beerus builds for various platforms/architectures and those will be attached to the github release in a tarball.

Issue can be closed after testing against our first release.

**Comment by LucasLvy** [comment]
fixed #92
