### ISSUE TITLE
Implement `verify_storage_proofs`

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/beerus#62]
## Description

We need to implement the verification of the storage proof when we access StarkNet state.
To do that we must use `pathfinder_getStorageProofs `endpoint.

The PR in PathFinder is here: https://github.com/eqlabs/pathfinder/pull/726
It has been merge.

## Acceptance criteria

- verify_storage_proofs is implemented in core library
- associated unit tests are implemented
- implementation is tested against a path finder node on a testnet

CLI and Rest API Wrapper will be done in follow up PRs.

**Comment by pscott** [comment]
Hey :) Down to work on this bad boy

**Comment by abdelhamidbakhta** [comment]
> Hey :) Down to work on this bad boy

Assigned it to you
