### ISSUE TITLE
feat: Ethereum RPC " get_block_by_hash" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#85]
# Description

Implement "get_block_by_hash" Ethereum RPC call

Helios implmentation: https://github.com/a16z/helios/blob/94bf458d941f30e34faeaa7d2484898dba54234d/client/src/rpc.rs#L81

# Acceptance Criteria

- Beerus can query a Ethereum's block number
- Associated cli command
- Associated rest api wrapper
- Helios integration
- Units tests
- Integration tests

**Comment by fkrause98** [comment]
I'll be working on this issue.
