### ISSUE TITLE
feat: Starknet RPC " get_transaction_by_hash" call 

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#89]
# Description

Implement "get_transaction_by_hash" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/da72d0130eb48cc84288c9948d983f5f78cf6054/starknet-providers/src/jsonrpc/mod.rs#L187

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Helios integration
- Units tests
- Integration tests

**Comment by mikiw** [comment]
I'll try to do it!

**Comment by abdelhamidbakhta** [comment]
> I'll try to do it!

Thanks, assigned it to you
