### ISSUE TITLE
feat: Starknet RPC "get_class" call

### ISSUE THREAD

**Issue by danilowhk** [keep-starknet-strange/beerus#90]
# Description

Implement "get_class" Starknet RPC call

Starknet-RS Implementation
https://github.com/xJonathanLEI/starknet-rs/blob/da72d0130eb48cc84288c9948d983f5f78cf6054/starknet-providers/src/jsonrpc/mod.rs#L227

# Acceptance Criteria

- Beerus can query a Starknet's block number
- Associated cli command
- Associated rest api wrapper
- Helios integration
- Units tests
- Integration tests

**Comment by ftupas** [comment]
Hello, may I take this one?
